### ISSUE TITLE
App crashes while searching for injected snippet

### ISSUE THREAD

**Issue by bachig26** [Protonosgit/Spicetify_Installer#16]
**Describe the bug**

I just found this project today (Dec.3, 2023) and tried to install it and the installer can't able to execute the program.

Device info: Windows 10

**Steps To Reproduce**

1. Go to 'Downloaded package [`v1.1.2`](https://github.com/Protonosgit/Spicetify_Installer/releases/download/1.1.2/Manager.exe)'
2. Double-Click to install.
3. the following error provided below appears.

**Additional context**

![Spicetify_Manager_v1 1 2_SBliEXi7mp](https://github.com/Protonosgit/Spicetify_Installer/assets/96393348/c4c92237-f66a-499d-b497-7d211dfe8ede)

**Comment by Protonosgit** [comment]
Seems to be related to the config file system.
This system is temporary and will be replaced within the next update with a more robust update checking tool which does not rely on config files at all.

Thank you for reporting!!

**Comment by Protonosgit** [comment]
Should be solved in [b461cc5](https://github.com/Protonosgit/Spicetify_Installer/commit/b461cc5d1e02f98a623557a229902801dfac99c6) and will be implemented in**1.1.3** .

First [testbuild](https://github.com/Protonosgit/Spicetify_Installer/actions/runs/7092043077) is available if you would like to check for any other errors.

**Comment by Protonosgit** [comment]
Please feel free to inform me if you encounter any other problems!

**Comment by bachig26** [comment]
> Please feel free to inform me if you encounter any other problems!

![Manager_3tJfIT7Og4](https://github.com/Protonosgit/Spicetify_Installer/assets/96393348/7d7ed7fd-84d1-453f-a25c-a4c2e6e134d8)

**Comment by bachig26** [comment]
> > Please feel free to inform me if you encounter any other problems!
> 
> ![Manager_3tJfIT7Og4](https://private-user-images.githubusercontent.com/96393348/287860775-7d7ed7fd-84d1-453f-a25c-a4c2e6e134d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjgxODEsIm5iZiI6MTcwMTc2Nzg4MSwicGF0aCI6Ii85NjM5MzM0OC8yODc4NjA3NzUtN2Q3ZWQ3ZmQtODRkMS00NTNmLWEyNWMtYTRjMmU2ZTEzNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZWY4NGE5ZDQ5Zjg5ZTNkN2I5N2E3MDlmOTY4Nzk1NzcyNzZjMTAxMTFmZmI3YmM5ZDM2NTE5Mzk3ZDY2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jHbDutn0PWf9_HX1ByeIRyDbKijjr0YuRbIaLJrE3O0)
> 
> i can only see these 3 files in that directory: `C:\Users\USER\AppData\Roaming\Spotify\Apps\`
> 
> ![explorer_G6kKhuWaeG](https://private-user-images.githubusercontent.com/96393348/287861464-d1ca3111-5033-4675-842d-addcc73fb7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjgxODEsIm5iZiI6MTcwMTc2Nzg4MSwicGF0aCI6Ii85NjM5MzM0OC8yODc4NjE0NjQtZDFjYTMxMTEtNTAzMy00Njc1LTg0MmQtYWRkY2M3M2ZiN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MmU0YjljOTY2NGI2ODAyYTFiMDJhN2FmZDJmNjhjZjI3ZjYwYWZmNDI0MDAyYzc2NGM3ODE1ODFlYWQ1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ck2hkm6CYdkveh_fkpn5TtVuLu21C3QILZyhJzmKTbA)

@Protonosgit

**Comment by Protonosgit** [comment]
I was not able to replicate this but this is most likely due to an older version of spicetify I am using.
The error comes from failing to verify that neccessary files are available in which need to be present in order for the startup server of the manager to recognize Spotify boot actions.
This is simlar to the config file issue which also had a problem with verifying code integrity.
I will try to work on this as soon as possible!
This error only occurs if Spicetify was never before installed on the machine.
Thank you for your help !

**Comment by Protonosgit** [comment]
Should be resolved with 
[0b8234e](https://github.com/Protonosgit/Spicetify_Installer/commit/0b8234e6b3720a0dcb9e13d8f79720089b26a4fa) but still needs a lot of work.
If you got time you can try out another [testbuild ](https://github.com/Protonosgit/Spicetify_Installer/actions/runs/7099102667)and open another issue if you find something.
Your support is always welcome!
