### ISSUE TITLE
Update button disables install button

### ISSUE THREAD

**Issue by BN-Net** [Protonosgit/Spicetify_Installer#7]
**Describe the bug**
Clicking update button hides launch / install button after checking version

**To Reproduce**
Click on update button and wait for check to finish

**OS/Platform:**
Windows

**Additional context**
~

**Comment by Protonosgit** [comment]
Fixed in [9ce3e48](https://github.com/Protonosgit/Spicetify_Installer/commit/9ce3e488439587ffd5fa3b3245e17c5e72a376cd)
