### ISSUE TITLE
App crashes after uninstall clicked

### ISSUE THREAD

**Issue by BN-Net** [Protonosgit/Spicetify_Installer#9]
**Describe the bug**
The uninstall button crashes the app when its pressed and spicetify is not installed

**To Reproduce**
1. Dont install spicetify
2. Click uninstall

**OS/Platform:**
Windows

**Comment by Protonosgit** [comment]
Will hopefully be fixed after [5992895](https://github.com/Protonosgit/Spicetify_Installer/commit/599289558968107ab46251b7a57b3a4f7e10e995)
